MAJ main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,28 +26,32 @@ jobs:
     steps:
       - name: Check du repository
         uses: actions/checkout@v3
-
-      - name: Vérifier la présence du Dockerfile
+  
+      - name: Vérifier la présence du Dockerfile et de nginx.conf
         run: |
           if [ ! -f Dockerfile ]; then
             echo "Dockerfile not found!"
             exit 1
           fi
+          if [ ! -f nginx.conf ]; then
+            echo "nginx.conf not found!"
+            exit 1
+          fi
         shell: bash
-
+  
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-
+  
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-
+  
       - name: Build Docker image
         run: |
           docker build -t my-docker-image:latest .
-          docker images  # Vérifier les images disponibles après la construction
+          docker images  # Vérifier la liste des images après la construction
 
       - name: Vérifier si l'image Docker est créée
         run: |
